server:
    port: 8080

management:
    endpoint:
        health:
            show-details: always

    endpoints.web.exposure.include: [ info, health, logfile, startup ]

app:
    url: http://localhost:8080/
    externalUrl: http://localhost:8080/
    dataSource:
        driverClassName: net.postgis.jdbc.DriverWrapper
        username: postgres
        password: postgres
        url: jdbc:postgresql_postGIS://localhost:5432/postgres
        maximumPoolSize: 8
        maxLifetime: 300000
        leakDetectionThreshold: 60000

    attachments:
        enabled: true
        store-type: directory
        base-url: ${app.externalUrl}
        directory:
            path: uploads

    dicts:
        storage: postgres
        engines: postgres
        default-engine: postgres
        ddl:
            scheme: dicts