services:
    db:
        image: postgres:${POSTGRES_VERSION}
        environment:
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"

    ui:
        image: git.backstage-platform.ru:5050/backstage/components/cms:latest

    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./cms-settings.json:/usr/share/nginx/html/cms-settings.json
        ports:
            - "80:80"
        extra_hosts:
            - "host.docker.internal:host-gateway"